name: Build and Push Docker Images

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.cdbPAT }}

    - name: Build and push images
      run: |
        for dockerfile in $(find . -name Dockerfile); do
          dir_of_image=$(dirname "$dockerfile")
          echo "Building image in $dir_of_image"
          image_name=$(dirname "$dockerfile")
          image_name=${image_name//\//-}
          docker_image_name="cinco-de-bio-${image_name//[^a-zA-Z0-9]/-}"

          if git log --quiet --diff-filter=A HEAD~1..HEAD -- "$image_name"; then
            echo "$image_name is a newly added path"
            docker build -t ghcr.io/${{ github.repository_owner }}/$docker_image_name:latest -f $dockerfile $dir_of_image
            docker push ghcr.io/${{ github.repository_owner }}/$docker_image_name:latest
          else
            echo "$image_name is not a newly added path"
            if git diff --quiet HEAD HEAD~1 -- "$image_name"; then
              echo "No changes in $image_name, skipping build"
            else
              docker build -t ghcr.io/${{ github.repository_owner }}/$docker_image_name:latest -f $dockerfile $dir_of_image
              docker push ghcr.io/${{ github.repository_owner }}/$docker_image_name:latest
            fi
          fi

          
        done